### ISSUE TITLE
Where can we download this?

### ISSUE THREAD

**Issue by sanvimerin** [gautamkrishnar/refined-github-feeds#2]
Is this available on chrome webstore? Is yes, why not sharing the link. Looks like an impressive work!

**Comment by gautamkrishnar** [comment]
Hi @sanvimerin thanks, yea i had already sumitted this to chrome webstore. It is under review right now. It may be deleyed further due to the COVID situation.

**Comment by gautamkrishnar** [comment]
@sanvimerin this is now available on all webstores: https://github.com/gautamkrishnar/refined-github-feeds#installing 🎉
