### ISSUE TITLE
Filter out following people stars

### ISSUE THREAD

**Issue by scmanjarrez** [gautamkrishnar/refined-github-feeds#3]
Hi, thank you very much for your extension, it helped me a lot filtering my feed.

Is it possible to add an option to filter stars from people I'm following?

**Comment by gautamkrishnar** [comment]
@scmanjarrez you can already filter out stars from the people you follow:

### Before
![Screenshot 2021-10-19 at 6 14 48 PM](https://user-images.githubusercontent.com/8397274/137911951-fd37c032-ab3d-4ddf-b077-89ec5e154836.png)

### After
![Screenshot 2021-10-19 at 6 18 27 PM](https://user-images.githubusercontent.com/8397274/137912423-76d0b745-7416-4e6c-8a27-a191e9c9cdbe.png)

**Comment by scmanjarrez** [comment]
But it removes the feeds from people starring your respositories as well, not only from your followings.
What I mean is:
- In your feed:
  - Stars from world to your repositories
- Filter out:
  - Stars from people you're following to any respository.

Without filtering:
![image](https://user-images.githubusercontent.com/9284124/137935621-e84861d6-30e3-421d-a694-14cba1a36cb8.png)
With stars filter enabled:
![image](https://user-images.githubusercontent.com/9284124/137935054-f970d738-bad7-4eeb-a6ed-2b497b14243c.png)
